package com.ccdelic.modus.oregen;

import com.electronwill.nightconfig.core.file.CommentedFileConfig;
import com.ccdelic.modus.Modus;
import com.ccdelic.modus.config.OreConfig;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.HashMap;
import java.util.IdentityHashMap;
import java.util.Map;
import net.minecraft.core.RegistryAccess;
import net.minecraft.core.registries.Registries;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.level.levelgen.feature.configurations.OreConfiguration;
import net.minecraft.world.level.levelgen.placement.PlacedFeature;
import net.neoforged.fml.ModList;
import net.neoforged.fml.loading.FMLPaths;

/**
 * Discovers every non-vanilla ore placed feature (any {@code PlacedFeature} whose feature
 * tree contains an {@link OreConfiguration}, from a namespace other than {@code minecraft}
 * and {@code modus}) at server start and gives each its own config file under
 * {@code config/Modus/oreOptions/modded/<Mod Name>/<ore>.toml}.
 * <p>
 * Unlike vanilla ores - which Modus controls by REPLACING their generation with its own
 * (see {@link com.ccdelic.modus.worldgen.ConfigurableOreBiomeModifier}), giving absolute
 * vein-size / count / height knobs - a modded ore is controlled by MULTIPLYING whatever the
 * mod already does, layered on top at generation time. That's deliberately more limited but
 * far more robust: it makes no assumptions about how the mod generates its ore, so it works
 * for mods using vanilla's ore feature and (for the frequency/disable controls) even mods
 * with entirely custom ore code, which reconstruction-based control could never handle.
 * <ul>
 *   <li>{@code enabled = false} vetoes the ore's generation entirely (its normal generation
 *   runs untouched when {@code true}, the default).</li>
 *   <li>{@code frequencyMultiplier} scales how many veins generate, by running the ore's
 *   placement extra times (or probabilistically skipping it) - applied in
 *   {@code BiomeDecorationOreMixin}, works for any ore regardless of its feature type.</li>
 *   <li>{@code sizeMultiplier} scales each vein's size - applied in {@code OreFeatureSizeMixin}
 *   / {@code ScatteredOreFeatureSizeMixin}, so it only affects ores generated by vanilla's
 *   own ore features (the common case); an ore placed by a mod's fully custom feature keeps
 *   its normal size. The effective size is always clamped to {@link OreConfig#MAX_SAFE_VEIN_SIZE}
 *   to avoid the "far chunk" world-gen boundary crash large veins can otherwise cause.</li>
 * </ul>
 * Discovery timing and the raw-TOML approach mirror
 * {@link com.ccdelic.modus.structures.StructureRarityRegistry} for the same reason: the set
 * of ores isn't known until a world's datapacks (and thus every installed mod's ore features)
 * have loaded, long after {@code ModConfigSpec} registration would need to run.
 */
public final class ModdedOreRegistry {
    public static final double MIN_FREQUENCY = 0.0;
    public static final double MAX_FREQUENCY = 10.0;
    public static final double MIN_SIZE_MULTIPLIER = 0.1;
    public static final double MAX_SIZE_MULTIPLIER = 10.0;

    private static volatile Map<PlacedFeature, Entry> byFeature = Map.of();
    private static volatile Map<ResourceLocation, Entry> byId = Map.of();
    private static volatile Map<ResourceLocation, PlacedFeature> featureById = Map.of();
    private static boolean authoritativeRefreshHasRun = false;

    private ModdedOreRegistry() {
    }

    /** True when at least one modded ore was discovered - a cheap gate for the hot mixin path. */
    public static boolean hasAny() {
        return !byFeature.isEmpty();
    }

    /** The managed entry for {@code feature}, or {@code null} if it isn't a discovered modded ore. */
    public static Entry get(PlacedFeature feature) {
        return byFeature.get(feature);
    }

    /** Every discovered modded ore keyed by its placed-feature id (for the config screen / logging). */
    public static Map<ResourceLocation, Entry> allEntries() {
        return byId;
    }

    /**
     * Persists one modded ore's entry back to its TOML file and updates the in-memory snapshot,
     * for {@code com.ccdelic.modus.client.ModdedOreScreen} to call when a value is edited.
     * Mirrors {@code StructureRarityRegistry#save}: safe to call from the render thread while a
     * server thread concurrently reads {@link #get} / {@link #hasAny}, via the same
     * volatile-snapshot swap.
     * <p>
     * Updates {@code byId} (for the screen's own display), and - via {@code featureById}, a
     * reverse index built alongside {@code byFeature} in {@link #doRefresh} specifically so
     * this lookup is possible - also {@code byFeature} itself, which is what
     * {@link #get(PlacedFeature)} (and therefore every mixin) actually reads during
     * generation. Without that second update, an edit made while a world is already running
     * (e.g. from the pause-menu config screen in singleplayer) would save to disk and update
     * the screen's own display, but silently have zero effect on that world's ongoing
     * generation until the next server start - unlike {@link StructureRarityRegistry}, whose
     * {@code get} reads the exact same map {@code save} writes, so its edits apply
     * immediately. Both registries were meant to behave the same way; this keeps them
     * consistent.
     */
    public static synchronized void save(ResourceLocation id, Entry entry) {
        Path baseDir = FMLPaths.CONFIGDIR.get().resolve(Modus.CONFIG_FOLDER).resolve("oreOptions").resolve("modded");
        Path file = baseDir.resolve(modFolderNameFor(id.getNamespace())).resolve(id.getPath() + ".toml");

        try (CommentedFileConfig config = CommentedFileConfig.builder(file).sync().build()) {
            if (Files.exists(file)) {
                config.load();
            }
            config.set("enabled", entry.enabled());
            config.set("frequencyMultiplier", entry.frequencyMultiplier());
            config.set("sizeMultiplier", entry.sizeMultiplier());
            config.save();
        } catch (Exception e) {
            Modus.LOGGER.error("Modus: failed to save modded ore config for {} at {}", id, file, e);
            return;
        }

        Map<ResourceLocation, Entry> updatedById = new HashMap<>(byId);
        updatedById.put(id, entry);
        byId = Map.copyOf(updatedById);

        PlacedFeature feature = featureById.get(id);
        if (feature != null) {
            Map<PlacedFeature, Entry> updatedByFeature = new IdentityHashMap<>(byFeature);
            updatedByFeature.put(feature, entry);
            byFeature = Map.copyOf(updatedByFeature);
        }
    }

    /**
     * Authoritative rebuild from a real server's registry access - called on every server start.
     * Once this has run at least once this session, {@link #refreshSpeculative} results are
     * discarded rather than allowed to overwrite it (same guard as {@code StructureRarityRegistry}).
     */
    public static synchronized void refresh(RegistryAccess registryAccess) {
        authoritativeRefreshHasRun = true;
        doRefresh(registryAccess);
    }

    /**
     * Speculative rebuild from {@code com.ccdelic.modus.client.WorldgenConfigBootstrap}'s
     * stand-in registry (default data packs, before any world exists), so the config screen
     * isn't empty at the main menu. Never overwrites an authoritative result.
     */
    public static synchronized void refreshSpeculative(RegistryAccess registryAccess) {
        if (authoritativeRefreshHasRun) {
            return;
        }
        doRefresh(registryAccess);
    }

    private static synchronized void doRefresh(RegistryAccess registryAccess) {
        Path baseDir = FMLPaths.CONFIGDIR.get().resolve(Modus.CONFIG_FOLDER).resolve("oreOptions").resolve("modded");

        Map<PlacedFeature, Entry> newByFeature = new IdentityHashMap<>();
        Map<ResourceLocation, Entry> newById = new HashMap<>();
        Map<ResourceLocation, PlacedFeature> newFeatureById = new HashMap<>();
        int nonVanillaScanned = 0;

        for (var holder : registryAccess.lookupOrThrow(Registries.PLACED_FEATURE).listElements().toList()) {
            ResourceLocation id = holder.key().location();
            String namespace = id.getNamespace();
            if (namespace.equals("minecraft") || namespace.equals(Modus.MODID)) {
                continue;
            }
            nonVanillaScanned++;

            PlacedFeature placedFeature;
            boolean ore;
            try {
                placedFeature = holder.value();
                ore = isOre(placedFeature);
            } catch (Exception e) {
                // A broken or oddly-registered feature from another mod must not abort discovery
                // of everything else - skip just this one and note it.
                Modus.LOGGER.warn("Modus: could not inspect placed feature {} while scanning for modded ores; skipping it.", id, e);
                continue;
            }

            if (!ore) {
                // Logged at DEBUG so a user whose modded ore ISN'T showing up can turn on debug
                // logging and see whether Modus even considered it (i.e. whether the mod places
                // its ore via a vanilla ore feature at all - the only kind auto-detection can find).
                Modus.LOGGER.debug("Modus: placed feature {} is not a vanilla-style ore feature; not auto-configured.", id);
                continue;
            }

            Path file = baseDir.resolve(modFolderNameFor(namespace)).resolve(id.getPath() + ".toml");
            Entry entry = loadOrCreate(file, id);
            newByFeature.put(placedFeature, entry);
            newById.put(id, entry);
            newFeatureById.put(id, placedFeature);
        }

        byFeature = newByFeature.isEmpty() ? Map.of() : newByFeature;
        byId = Map.copyOf(newById);
        featureById = Map.copyOf(newFeatureById);
        Modus.LOGGER.info(
            "Modus: loaded modded ore config for {} ore(s) (scanned {} non-vanilla placed features)",
            newById.size(), nonVanillaScanned
        );
        if (!newById.isEmpty()) {
            Modus.LOGGER.info("Modus: modded ores auto-configured: {}", newById.keySet().stream().sorted().toList());
        }
    }

    /**
     * True if this placed feature generates a vanilla-style ore vein anywhere in its feature
     * tree ({@link OreConfiguration}, i.e. {@code minecraft:ore} / {@code minecraft:scattered_ore}
     * - what the vast majority of ore mods use). Ores placed by a mod's fully custom feature
     * aren't recognizable this way and won't be auto-configured; that limitation is documented
     * for users (turn on debug logging to see which of a mod's features were skipped).
     */
    private static boolean isOre(PlacedFeature placedFeature) {
        return placedFeature.getFeatures().anyMatch(configured -> configured.config() instanceof OreConfiguration);
    }

    private static String modFolderNameFor(String namespace) {
        return ModList.get().getModContainerById(namespace)
            .map(container -> sanitizeForPath(container.getModInfo().getDisplayName()))
            .orElseGet(() -> sanitizeForPath(namespace));
    }

    private static String sanitizeForPath(String name) {
        String sanitized = name.replaceAll("[\\\\/:*?\"<>|]", "_").trim();
        return sanitized.isEmpty() ? "unknown" : sanitized;
    }

    private static Entry loadOrCreate(Path file, ResourceLocation id) {
        try {
            boolean existed = Files.exists(file);
            Files.createDirectories(file.getParent());

            try (CommentedFileConfig config = CommentedFileConfig.builder(file).sync().build()) {
                if (existed) {
                    config.load();
                } else {
                    config.set("enabled", true);
                    config.setComment("enabled", " Whether " + id + " is allowed to generate. false disables it entirely.");
                    config.set("frequencyMultiplier", 1.0);
                    config.setComment(
                        "frequencyMultiplier",
                        " How many veins generate, relative to the mod's own rate.\n"
                            + " 1.0 = unchanged, 2.0 = twice as many, 0.5 = half as many.\n"
                            + " Range: " + MIN_FREQUENCY + " ~ " + MAX_FREQUENCY
                    );
                    config.set("sizeMultiplier", 1.0);
                    config.setComment(
                        "sizeMultiplier",
                        " Size of each vein, relative to the mod's own size (vanilla-ore-feature ores only).\n"
                            + " 1.0 = unchanged, 2.0 = twice as big, 0.5 = half. Effective size is capped at "
                            + OreConfig.MAX_SAFE_VEIN_SIZE + ".\n"
                            + " Range: " + MIN_SIZE_MULTIPLIER + " ~ " + MAX_SIZE_MULTIPLIER
                    );
                    config.save();
                }

                boolean enabled = config.getOrElse("enabled", true);
                double frequency = clamp(readDouble(config, "frequencyMultiplier", 1.0), MIN_FREQUENCY, MAX_FREQUENCY);
                double size = clamp(readDouble(config, "sizeMultiplier", 1.0), MIN_SIZE_MULTIPLIER, MAX_SIZE_MULTIPLIER);
                return new Entry(enabled, frequency, size);
            }
        } catch (Exception e) {
            Modus.LOGGER.error("Modus: failed to load modded ore config for {} at {}; using defaults.", id, file, e);
            return Entry.DEFAULT;
        }
    }

    private static double readDouble(CommentedFileConfig config, String key, double fallback) {
        Number value = config.get(key);
        return value != null ? value.doubleValue() : fallback;
    }

    private static double clamp(double value, double min, double max) {
        if (Double.isNaN(value) || Double.isInfinite(value)) {
            return 1.0;
        }
        return Math.max(min, Math.min(max, value));
    }

    public record Entry(boolean enabled, double frequencyMultiplier, double sizeMultiplier) {
        public static final Entry DEFAULT = new Entry(true, 1.0, 1.0);
    }
}
