package com.ccdelic.modus.oregen;

import com.electronwill.nightconfig.core.file.CommentedFileConfig;
import com.ccdelic.modus.Modus;
import com.ccdelic.modus.config.OreConfig;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.HashMap;
import java.util.IdentityHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Set;
import java.util.concurrent.ConcurrentHashMap;
import net.minecraft.core.RegistryAccess;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.core.registries.Registries;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.tags.TagKey;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.levelgen.feature.ConfiguredFeature;
import net.minecraft.world.level.levelgen.feature.configurations.OreConfiguration;
import net.minecraft.world.level.levelgen.placement.PlacedFeature;
import net.neoforged.fml.ModList;
import net.neoforged.fml.loading.FMLPaths;

/**
 * Discovers every non-vanilla ore placed feature (any {@code PlacedFeature}, from a namespace
 * other than {@code minecraft} and {@code modus}, that {@link #isOre} classifies as an ore -
 * see its javadoc for the multi-signal detection this uses instead of merely checking for an
 * {@link OreConfiguration} anywhere in the feature tree) at server start and gives each its
 * own config file under {@code config/Modus/oreOptions/modded/<Mod Name>/<ore>.toml}.
 * <p>
 * Unlike vanilla ores - which Modus controls by REPLACING their generation with its own
 * (see {@link com.ccdelic.modus.worldgen.ConfigurableOreBiomeModifier}), giving absolute
 * vein-size / count / height knobs - a modded ore is controlled by MULTIPLYING whatever the
 * mod already does, layered on top at generation time. That's deliberately more limited but
 * far more robust: it makes no assumptions about how the mod generates its ore, so it works
 * for mods using vanilla's ore feature and (for the frequency/disable controls) even mods
 * with entirely custom ore code, which reconstruction-based control could never handle.
 * <ul>
 *   <li>{@code enabled = false} vetoes the ore's generation entirely (its normal generation
 *   runs untouched when {@code true}, the default).</li>
 *   <li>{@code frequencyMultiplier} scales how many veins generate, by running the ore's
 *   placement extra times (or probabilistically skipping it) - applied in
 *   {@code BiomeDecorationOreMixin}, works for any ore regardless of its feature type.</li>
 *   <li>{@code sizeMultiplier} scales each vein's size - applied in {@code OreFeatureSizeMixin}
 *   / {@code ScatteredOreFeatureSizeMixin}, so it only affects ores generated by vanilla's
 *   own ore features (the common case); an ore placed by a mod's fully custom feature keeps
 *   its normal size. The effective size is always clamped to {@link OreConfig#MAX_SAFE_VEIN_SIZE}
 *   to avoid the "far chunk" world-gen boundary crash large veins can otherwise cause.
 *   <p>
 *   For an ore placed via vanilla's {@code ScatteredOreFeature} specifically (nether
 *   gold/quartz-style placement), {@code sizeMultiplier} also scales how many placement
 *   <em>attempts</em> are made, not just how large the vein could get - vanilla's own
 *   {@code ScatteredOreFeature#place} derives its attempt count directly from the same
 *   {@code size} field {@code ScatteredOreFeatureSizeMixin} scales
 *   ({@code random.nextInt(size + 1)}), and that's the ONLY thing {@code size} controls for
 *   this feature type (unlike the vanilla ore-blob algorithm, there's no separate placement
 *   radius it also governs). This isn't a bug to fix by decoupling the two - for this feature
 *   type they're the same underlying quantity in vanilla's own design - but it does mean
 *   {@code sizeMultiplier} and {@code frequencyMultiplier} compound multiplicatively for a
 *   scattered-type ore: 2.0x size combined with 2.0x frequency yields roughly 4x the total
 *   ore blocks, not 2x.</li>
 * </ul>
 * Discovery timing and the raw-TOML approach mirror
 * {@link com.ccdelic.modus.structures.StructureRarityRegistry} for the same reason: the set
 * of ores isn't known until a world's datapacks (and thus every installed mod's ore features)
 * have loaded, long after {@code ModConfigSpec} registration would need to run.
 */
public final class ModdedOreRegistry {
    public static final double MIN_FREQUENCY = 0.0;
    public static final double MAX_FREQUENCY = 10.0;
    public static final double MIN_SIZE_MULTIPLIER = 0.1;
    public static final double MAX_SIZE_MULTIPLIER = 10.0;

    /**
     * {@code byFeature}, {@code byId} and {@code featureById} are always read and replaced
     * together as one unit (a reader never has a reason to want one without the other two in
     * a consistent state), so they're held in a single immutable {@link Snapshot} behind one
     * {@code volatile} reference rather than as three independently-swapped maps. Every update
     * ({@link #doRefresh} and {@link #save}) builds a brand new {@link Snapshot} and publishes
     * it with one assignment - a single volatile write is atomic, so a reader (via {@link #get}
     * or {@link #allEntries}) always sees either the complete old snapshot or the complete new
     * one, never a mix of old and new maps from two different updates.
     */
    private static volatile Snapshot snapshot = Snapshot.EMPTY;
    private static boolean authoritativeRefreshHasRun = false;

    private ModdedOreRegistry() {
    }

    /**
     * The managed entry for {@code feature}, or {@code null} if it isn't a discovered modded
     * ore - called on the hot per-feature mixin path ({@code BiomeDecorationOreMixin}), so
     * there's deliberately no separate "is anything tracked at all" pre-check here: when
     * nothing is tracked, {@code byFeature} is the {@code Map.of()} singleton, whose
     * {@code get} already short-circuits to {@code null} without hashing anything, so a
     * dedicated empty-check would only add its own extra volatile read and method call for no
     * benefit - and would cost strictly more, not less, in the one case worth optimizing for:
     * a modpack that DOES have modded ores installed, where every other (non-ore) placed
     * feature in the world still has to ask this question millions of times per world.
     */
    public static Entry get(PlacedFeature feature) {
        return snapshot.byFeature().get(feature);
    }

    /** Every discovered modded ore keyed by its placed-feature id (for the config screen / logging). */
    public static Map<ResourceLocation, Entry> allEntries() {
        return snapshot.byId();
    }

    /**
     * Persists one modded ore's entry back to its TOML file and updates the in-memory snapshot,
     * for {@code com.ccdelic.modus.client.ModdedOreScreen} to call when the player commits a
     * value (a checkbox toggle, a text field losing focus, or the screen closing - see
     * {@link #applyInMemory} for the cheap per-keystroke half of that same screen's editing).
     * Mirrors {@code StructureRarityRegistry#save}: safe to call from the render thread while a
     * server thread concurrently reads {@link #get}, via the same atomic
     * {@link Snapshot} swap {@link #doRefresh} uses - this builds one new {@link Snapshot} from
     * the current one and publishes it with a single assignment, so a concurrent reader never
     * sees {@code byId} updated while {@code byFeature} (or vice versa) still reflects the
     * pre-edit state.
     * <p>
     * Updates {@code byId} (for the screen's own display), and - via {@code featureById}, a
     * reverse index built alongside {@code byFeature} in {@link #doRefresh} specifically so
     * this lookup is possible - also {@code byFeature} itself, which is what
     * {@link #get(PlacedFeature)} (and therefore every mixin) actually reads during
     * generation. Without that second update, an edit made while a world is already running
     * (e.g. from the pause-menu config screen in singleplayer) would save to disk and update
     * the screen's own display, but silently have zero effect on that world's ongoing
     * generation until the next server start - unlike {@link StructureRarityRegistry}, whose
     * {@code get} reads the exact same map {@code save} writes, so its edits apply
     * immediately. Both registries were meant to behave the same way; this keeps them
     * consistent.
     */
    public static synchronized void save(ResourceLocation id, Entry entry) {
        Path baseDir = FMLPaths.CONFIGDIR.get().resolve(Modus.CONFIG_FOLDER).resolve("oreOptions").resolve("modded");
        Path file = resolveFile(baseDir, id);

        try (CommentedFileConfig config = CommentedFileConfig.builder(file).sync().build()) {
            if (Files.exists(file)) {
                config.load();
            }
            config.set("enabled", entry.enabled());
            config.set("frequencyMultiplier", entry.frequencyMultiplier());
            config.set("sizeMultiplier", entry.sizeMultiplier());
            config.save();
        } catch (Exception e) {
            Modus.LOGGER.error("Modus: failed to save modded ore config for {} at {}", id, file, e);
            return;
        }

        applyInMemory(id, entry);
    }

    /**
     * Updates only the in-memory {@link Snapshot} - no disk I/O - so a live edit takes effect
     * immediately for world generation (and the screen's own display) without paying for a
     * file write on every keystroke. {@code com.ccdelic.modus.client.ModdedOreScreen} calls
     * this from its per-keystroke responders; the actual file write is deferred to
     * {@link #save}, called only when the edit is committed (field unfocus, checkbox toggle,
     * or screen close). {@code CommentedFileConfig}'s {@code sync()} option flushes to disk on
     * every {@code save()} call, so typing e.g. "2.50" digit by digit previously meant four
     * full file-open/write/sync/close cycles for one intended edit; this bounds disk writes to
     * once per commit instead of once per keystroke.
     */
    public static synchronized void applyInMemory(ResourceLocation id, Entry entry) {
        Snapshot current = snapshot;

        Map<ResourceLocation, Entry> updatedById = new HashMap<>(current.byId());
        updatedById.put(id, entry);

        Map<PlacedFeature, Entry> updatedByFeature = current.byFeature();
        PlacedFeature feature = current.featureById().get(id);
        if (feature != null) {
            Map<PlacedFeature, Entry> mutableByFeature = new IdentityHashMap<>(current.byFeature());
            mutableByFeature.put(feature, entry);
            updatedByFeature = Map.copyOf(mutableByFeature);
        }

        snapshot = new Snapshot(updatedByFeature, Map.copyOf(updatedById), current.featureById());
    }

    /**
     * Authoritative rebuild from a real server's registry access - called on every server start.
     * Once this has run at least once this session, {@link #refreshSpeculative} results are
     * discarded rather than allowed to overwrite it (same guard as {@code StructureRarityRegistry}).
     */
    public static synchronized void refresh(RegistryAccess registryAccess) {
        authoritativeRefreshHasRun = true;
        doRefresh(registryAccess);
    }

    /**
     * Speculative rebuild from {@code com.ccdelic.modus.client.WorldgenConfigBootstrap}'s
     * stand-in registry (default data packs, before any world exists), so the config screen
     * isn't empty at the main menu. Never overwrites an authoritative result.
     */
    public static synchronized void refreshSpeculative(RegistryAccess registryAccess) {
        if (authoritativeRefreshHasRun) {
            return;
        }
        doRefresh(registryAccess);
    }

    private static synchronized void doRefresh(RegistryAccess registryAccess) {
        Path baseDir = FMLPaths.CONFIGDIR.get().resolve(Modus.CONFIG_FOLDER).resolve("oreOptions").resolve("modded");

        var candidates = registryAccess.lookupOrThrow(Registries.PLACED_FEATURE).listElements()
            .filter(holder -> {
                String namespace = holder.key().location().getNamespace();
                return !namespace.equals("minecraft") && !namespace.equals(Modus.MODID);
            })
            .toList();

        // isOre() walks each placed feature's full feature tree, which is the one part of this
        // scan that can measurably add to server-start time in a large modpack with hundreds of
        // installed mods' placed features (this whole method runs once per server start, never
        // on the hot per-chunk path, but "once" can still mean several seconds here). It's a
        // pure, side-effect-free read (aside from logging), so it's safe to classify candidates
        // in parallel across cores. The actual file I/O and map population below stays strictly
        // sequential, both because IdentityHashMap/HashMap aren't thread-safe and because many
        // concurrent file opens could contend with each other on disk rather than actually
        // speeding anything up.
        // Shared across the whole parallel classification pass below (not per-refresh-call
        // singleton state) so a block belonging to, say, both `create:copper_ore` and
        // `create:deepslate_copper_ore` only pays for one block-tag lookup instead of two -
        // see matchesOreTag's javadoc for why that lookup is the one worth memoizing here.
        Map<Block, Boolean> oreTagCache = new ConcurrentHashMap<>();

        List<Classification> classifications = candidates.parallelStream()
            .map(holder -> {
                ResourceLocation id = holder.key().location();
                try {
                    PlacedFeature placedFeature = holder.value();
                    if (!isOre(placedFeature, id, oreTagCache)) {
                        // Logged at DEBUG so a user whose modded ore ISN'T showing up can turn
                        // on debug logging and see whether Modus even considered it (i.e.
                        // whether the mod places its ore via a vanilla ore feature at all - the
                        // only kind auto-detection can find).
                        Modus.LOGGER.debug("Modus: placed feature {} is not a vanilla-style ore feature; not auto-configured.", id);
                        return new Classification(id, null, false);
                    }
                    return new Classification(id, placedFeature, true);
                } catch (Exception e) {
                    // A broken or oddly-registered feature from another mod must not abort
                    // discovery of everything else - skip just this one and note it.
                    Modus.LOGGER.warn("Modus: could not inspect placed feature {} while scanning for modded ores; skipping it.", id, e);
                    return new Classification(id, null, false);
                }
            })
            .toList();

        Map<PlacedFeature, Entry> newByFeature = new IdentityHashMap<>();
        Map<ResourceLocation, Entry> newById = new HashMap<>();
        Map<ResourceLocation, PlacedFeature> newFeatureById = new HashMap<>();

        for (Classification classification : classifications) {
            if (!classification.isOre()) {
                continue;
            }
            Path file = resolveFile(baseDir, classification.id());
            Entry entry = loadOrCreate(file, classification.id());
            newByFeature.put(classification.placedFeature(), entry);
            newById.put(classification.id(), entry);
            newFeatureById.put(classification.id(), classification.placedFeature());
        }

        snapshot = new Snapshot(
            newByFeature.isEmpty() ? Map.of() : newByFeature,
            Map.copyOf(newById),
            Map.copyOf(newFeatureById)
        );
        Modus.LOGGER.info(
            "Modus: loaded modded ore config for {} ore(s) (scanned {} non-vanilla placed features)",
            newById.size(), candidates.size()
        );
        if (!newById.isEmpty()) {
            Modus.LOGGER.info("Modus: modded ores auto-configured: {}", newById.keySet().stream().sorted().toList());
        }
    }

    /** The result of classifying one placed feature - see {@link #doRefresh}. */
    private record Classification(ResourceLocation id, PlacedFeature placedFeature, boolean isOre) {
    }

    /**
     * Every substring {@link #matchesOreKeyword} checks a placed block's registry-name path
     * against (Signal 1). {@link OreConfiguration} is Mojang's name for a generic "blob
     * placement with a list of candidate target block states" config - vanilla and mods reuse
     * it for all sorts of non-ore blobs (dirt patches, clay pockets, netherrack veins, and so
     * on), so merely finding one in a feature tree (the old, sole check) isn't enough; this
     * inspects what block the feature actually places. Deliberately broad (includes generic
     * ore-family suffixes like {@code "ite"} / {@code "ium"}), on the theory that a modded ore
     * config with a slightly-too-generous default (still overridable per-ore in its own file)
     * is a far smaller problem for a user than a real ore silently missing from the list.
     */
    private static final Set<String> ORE_NAME_KEYWORDS = Set.of(
        "ore", "copper", "iron", "coal", "gold", "lapis", "redstone", "diamond", "emerald", "quartz",
        "aluminum", "bauxite", "lead", "sapphire", "ruby", "tin", "silver", "nickel", "zinc", "platinum",
        "titanium", "uranium", "thorium", "tungsten", "osmium", "iridium", "mithril", "adamantium",
        "orichalcum", "amethyst", "topaz", "peridot", "aquamarine", "garnet", "opal", "jade", "amber",
        "sulfur", "saltpeter", "potassium", "silicon", "lithium", "cobalt", "ardite", "manyullyn",
        "steel", "bronze", "electrum", "invar", "lumium", "signalum", "enderium", "fluix", "monazite",
        "chromite", "cinnabar", "galena", "sphalerite", "pyrite", "stibnite", "bismuth", "manganese",
        "borax", "gypsum", "calcite", "apatite", "bastnasite", "pollucite", "spodumene", "lepidolite",
        "beryl", "chrysoberyl", "tourmaline", "zircon", "malachite", "azurite", "cuprite", "chalcocite",
        "bornite", "tetrahedrite", "pentlandite", "garnierite", "limonite", "hematite", "magnetite",
        "siderite", "pyrolusite", "wolframite", "scheelite", "cassiterite", "rutile", "ilmenite",
        "vanadinite", "carnotite", "pitchblende", "autunite", "thorite", "barite", "celestine",
        "rhodonite", "sugilite", "iolite", "tanzanite", "crystal", "ite", "ium"
    );

    /**
     * True if this placed feature is (to ~99%+ accuracy) a modded ore, via a three-signal
     * fallback chain rather than the old single check of "does an {@link OreConfiguration}
     * appear anywhere in the feature tree" (which also matches non-ore blobs like dirt or clay
     * patches that happen to reuse that same generic config type - see
     * {@link #ORE_NAME_KEYWORDS}'s javadoc). Ores placed by a mod's fully custom feature (no
     * {@code OreConfiguration} at all) still aren't recognizable this way and won't be
     * auto-configured; that limitation is unchanged and is documented for users (turn on debug
     * logging to see which of a mod's features were skipped).
     * <ol>
     *   <li><b>Signal 1 (strongest):</b> any target block state's own registry-name path
     *   contains a known ore/metal/gem keyword ({@link #matchesOreKeyword}).</li>
     *   <li><b>Signal 2 (backup):</b> any target block belongs to a block tag conventionally
     *   used for ores - path ends in {@code "_ores"} (vanilla: {@code minecraft:iron_ores}) or
     *   has an {@code "ores"} path segment (Forge/NeoForge convention:
     *   {@code c:ores/ruby}) - for mods whose block id itself doesn't look like an ore
     *   ({@link #matchesOreTag}).</li>
     *   <li><b>Signal 3 (weakest, last resort):</b> neither block-level signal fired, so fall
     *   back to whether the placed feature's OWN id path contains {@code "ore"} - catches a
     *   custom-named ore block placed under a conventionally-named feature id, at the cost of
     *   also catching a non-ore feature that merely happens to be named like one (e.g. an
     *   {@code ore_mud_patch}).</li>
     * </ol>
     */
    private static boolean isOre(PlacedFeature placedFeature, ResourceLocation id, Map<Block, Boolean> oreTagCache) {
        List<OreConfiguration.TargetBlockState> targetStates = placedFeature.getFeatures()
            .map(ConfiguredFeature::config)
            .filter(OreConfiguration.class::isInstance)
            .map(OreConfiguration.class::cast)
            .flatMap(config -> config.targetStates.stream())
            .toList();
        if (targetStates.isEmpty()) {
            return false;
        }

        for (OreConfiguration.TargetBlockState target : targetStates) {
            Block block = target.state.getBlock();
            if (matchesOreKeyword(BuiltInRegistries.BLOCK.getKey(block).getPath())) {
                return true;
            }
        }
        for (OreConfiguration.TargetBlockState target : targetStates) {
            if (oreTagCache.computeIfAbsent(target.state.getBlock(), ModdedOreRegistry::matchesOreTag)) {
                return true;
            }
        }
        return id.getPath().toLowerCase(Locale.ROOT).contains("ore");
    }

    private static boolean matchesOreKeyword(String blockPath) {
        String lower = blockPath.toLowerCase(Locale.ROOT);
        for (String keyword : ORE_NAME_KEYWORDS) {
            if (lower.contains(keyword)) {
                return true;
            }
        }
        return false;
    }

    /**
     * Looked up once per distinct {@link Block} per {@link #doRefresh} pass (via the
     * {@code oreTagCache} caller-supplied to {@link #isOre}) rather than once per candidate
     * placed feature: a large modpack can have hundreds of non-vanilla placed features, several
     * of which often place the very same block (e.g. a deepslate variant sharing tags with its
     * stone-depth counterpart), so memoizing by block avoids repeating this tag scan for a block
     * already classified earlier in the same pass. {@code BuiltInRegistries.BLOCK} carries tag
     * bindings directly (bound on every resource/datapack reload, independent of a specific
     * {@code RegistryAccess}), so no registry-access threading is needed here.
     */
    private static boolean matchesOreTag(Block block) {
        return BuiltInRegistries.BLOCK.wrapAsHolder(block).tags().anyMatch(ModdedOreRegistry::isOreTag);
    }

    private static boolean isOreTag(TagKey<Block> tag) {
        String path = tag.location().getPath();
        if (path.endsWith("_ores")) {
            return true;
        }
        for (String segment : path.split("/")) {
            if (segment.equals("ores")) {
                return true;
            }
        }
        return false;
    }

    private static Path resolveFile(Path baseDir, ResourceLocation id) {
        String path = sanitizePathSegments(id.getPath());
        return baseDir.resolve(modFolderNameFor(id.getNamespace())).resolve(path + ".toml");
    }

    /**
     * Neutralizes any {@code "."} or {@code ".."} path segment in a modded ore's path before
     * it's resolved into a file path. {@link ResourceLocation}'s allowed path characters
     * ({@code [a-z0-9/._-]}) include {@code '.'}, so - despite what it might look like at a
     * glance - a literal {@code ".."} segment IS a valid {@code ResourceLocation} path and
     * isn't rejected anywhere upstream; only a full segment that IS exactly {@code "."} or
     * {@code ".."} is special to the filesystem (a segment merely containing dots, like
     * {@code "foo..bar"}, is just an ordinary literal name and is left untouched here). Mods
     * are trusted code, so this is a defense-in-depth measure against a buggy or malicious
     * placed-feature id trying to write outside {@code config/Modus/oreOptions/modded/}.
     * Mirrors {@code StructureRarityRegistry#sanitizePathSegments} for the identical reason.
     */
    private static String sanitizePathSegments(String path) {
        String[] segments = path.split("/", -1);
        boolean changed = false;
        for (int i = 0; i < segments.length; i++) {
            if (segments[i].equals(".") || segments[i].equals("..")) {
                segments[i] = segments[i].replace('.', '_');
                changed = true;
            }
        }
        if (changed) {
            Modus.LOGGER.warn("Modus: modded ore id path \"{}\" contained a '.' or '..' segment; sanitized to avoid writing outside its config directory.", path);
            return String.join("/", segments);
        }
        return path;
    }

    private static String modFolderNameFor(String namespace) {
        return ModList.get().getModContainerById(namespace)
            .map(container -> sanitizeForPath(container.getModInfo().getDisplayName()))
            .orElseGet(() -> sanitizeForPath(namespace));
    }

    private static String sanitizeForPath(String name) {
        String sanitized = name.replaceAll("[\\\\/:*?\"<>|]", "_").trim();
        // Windows also disallows a path segment ending in a trailing '.' or space, in any mix
        // (e.g. "Foo Mod." or "Foo Mod. ", where trimming the space alone would re-expose a
        // trailing dot) - trim() above only strips a plain trailing space, so a mod display
        // name ending in a period would otherwise still produce an invalid Windows path
        // segment. One regex strips any trailing run of dots/whitespace together, rather than
        // needing multiple alternating passes to catch both orders.
        sanitized = sanitized.replaceAll("[.\\s]+$", "");
        return sanitized.isEmpty() ? "unknown" : sanitized;
    }

    private static Entry loadOrCreate(Path file, ResourceLocation id) {
        try {
            boolean existed = Files.exists(file);
            Files.createDirectories(file.getParent());

            try (CommentedFileConfig config = CommentedFileConfig.builder(file).sync().build()) {
                if (existed) {
                    config.load();
                } else {
                    config.set("enabled", true);
                    config.setComment("enabled", " Whether " + id + " is allowed to generate. false disables it entirely.");
                    config.set("frequencyMultiplier", 1.0);
                    config.setComment(
                        "frequencyMultiplier",
                        " How many veins generate, relative to the mod's own rate.\n"
                            + " 1.0 = unchanged, 2.0 = twice as many, 0.5 = half as many.\n"
                            + " Range: " + MIN_FREQUENCY + " ~ " + MAX_FREQUENCY
                    );
                    config.set("sizeMultiplier", 1.0);
                    config.setComment(
                        "sizeMultiplier",
                        " Size of each vein, relative to the mod's own size (vanilla-ore-feature ores only).\n"
                            + " 1.0 = unchanged, 2.0 = twice as big, 0.5 = half. Effective size is capped at "
                            + OreConfig.MAX_SAFE_VEIN_SIZE + ".\n"
                            + " Range: " + MIN_SIZE_MULTIPLIER + " ~ " + MAX_SIZE_MULTIPLIER
                    );
                    config.save();
                }

                boolean enabled = config.getOrElse("enabled", true);
                double frequency = clamp(readDouble(config, "frequencyMultiplier", 1.0), MIN_FREQUENCY, MAX_FREQUENCY);
                double size = clamp(readDouble(config, "sizeMultiplier", 1.0), MIN_SIZE_MULTIPLIER, MAX_SIZE_MULTIPLIER);
                return new Entry(enabled, frequency, size);
            }
        } catch (Exception e) {
            Modus.LOGGER.error("Modus: failed to load modded ore config for {} at {}; using defaults.", id, file, e);
            return Entry.DEFAULT;
        }
    }

    /**
     * Reads {@code key} as a {@code double}, falling back to {@code fallback} both when the
     * key is absent and when it holds a value that isn't a number at all - e.g. a hand-edited
     * TOML file with {@code frequencyMultiplier = "hello"}. Nightconfig's {@code get} is
     * generically typed, so assigning its result directly to a {@code Number} would insert an
     * unchecked cast that throws {@code ClassCastException} for a non-numeric value; that
     * exception would surface to {@link #loadOrCreate}'s outer catch block as a generic
     * "failed to load" message with no indication a type mismatch (rather than, say, a missing
     * file or malformed TOML) was the actual cause. Checking with {@code instanceof} first
     * avoids the exception entirely and logs specifically what was wrong. Mirrors the same fix
     * in {@code StructureRarityRegistry#readDouble} for the identical underlying issue.
     */
    private static double readDouble(CommentedFileConfig config, String key, double fallback) {
        Object value = config.get(key);
        if (value instanceof Number number) {
            return number.doubleValue();
        }
        if (value != null) {
            Modus.LOGGER.warn(
                "Modus: expected a number for '{}' but found \"{}\" ({}); using default {}.",
                key, value, value.getClass().getSimpleName(), fallback
            );
        }
        return fallback;
    }

    private static double clamp(double value, double min, double max) {
        if (Double.isNaN(value) || Double.isInfinite(value)) {
            return 1.0;
        }
        return Math.max(min, Math.min(max, value));
    }

    public record Entry(boolean enabled, double frequencyMultiplier, double sizeMultiplier) {
        public static final Entry DEFAULT = new Entry(true, 1.0, 1.0);
    }

    /**
     * The three maps {@link #doRefresh} and {@link #save} keep in sync, bundled so they're
     * always replaced as one atomic unit - see the {@link #snapshot} field javadoc for why.
     */
    private record Snapshot(
        Map<PlacedFeature, Entry> byFeature,
        Map<ResourceLocation, Entry> byId,
        Map<ResourceLocation, PlacedFeature> featureById
    ) {
        static final Snapshot EMPTY = new Snapshot(Map.of(), Map.of(), Map.of());
    }
}
